//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LuyenThiTracNghiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOI
    {
        public string Macauhoi { get; set; }
        public string Noidungcauhoi { get; set; }
        public string NoidungcauA { get; set; }
        public string NoidungcauB { get; set; }
        public string NoidungcauC { get; set; }
        public string NoidungcauD { get; set; }
        public string Dapan { get; set; }
        public string Madethi { get; set; }
    
        public virtual DETHI DETHI { get; set; }
    }
}
