//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LuyenThiTracNghiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANGVIEN
    {
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public string Diachi { get; set; }
        public Nullable<decimal> SDT { get; set; }
        public string email { get; set; }
        public string Malop { get; set; }
        public string MaAdmin { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        public virtual LOPHOC LOPHOC { get; set; }
        public virtual Quantrivien Quantrivien { get; set; }
    }
}
