//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LuyenThiTracNghiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCVIEN()
        {
            this.LOPHOCs = new HashSet<LOPHOC>();
        }
    
        public string MaHV { get; set; }
        public string TenHV { get; set; }
        public string TenLopHoc { get; set; }
        public string Madethi { get; set; }
        public string Diachi { get; set; }
        public Nullable<decimal> SDT { get; set; }
        public string email { get; set; }
        public string Ketqua { get; set; }
        public Nullable<int> tongsocautraloidung { get; set; }
        public string MaAdmin { get; set; }
        public Nullable<System.DateTime> NgayThi { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        public virtual DETHI DETHI { get; set; }
        public virtual Quantrivien Quantrivien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOPHOC> LOPHOCs { get; set; }
    }
}
