//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LuyenThiTracNghiem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LuyenThiTracNghiemEntities2 : DbContext
    {
        public LuyenThiTracNghiemEntities2()
            : base("name=LuyenThiTracNghiemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAUHOI> CAUHOIs { get; set; }
        public virtual DbSet<DETHI> DETHIs { get; set; }
        public virtual DbSet<GIANGVIEN> GIANGVIENs { get; set; }
        public virtual DbSet<HOCVIEN> HOCVIENs { get; set; }
        public virtual DbSet<LOPHOC> LOPHOCs { get; set; }
        public virtual DbSet<MONHOC> MONHOCs { get; set; }
        public virtual DbSet<QUANLYCHUONG> QUANLYCHUONGs { get; set; }
        public virtual DbSet<Quantrivien> Quantriviens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
