//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LuyenThiTracNghiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONHOC()
        {
            this.DETHIs = new HashSet<DETHI>();
            this.QUANLYCHUONGs = new HashSet<QUANLYCHUONG>();
        }
    
        public int IdMonhoc { get; set; }
        public string Mamonhoc { get; set; }
        public string Tenmonhoc { get; set; }
        public string MaAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETHI> DETHIs { get; set; }
        public virtual Quantrivien Quantrivien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANLYCHUONG> QUANLYCHUONGs { get; set; }
    }
}
