//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LuyenThiTracNghiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLYCHUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUANLYCHUONG()
        {
            this.DETHIs = new HashSet<DETHI>();
        }
    
        public string MaChuong { get; set; }
        public string TenChuong { get; set; }
        public string MaAdmin { get; set; }
        public Nullable<int> IdMonhoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETHI> DETHIs { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual Quantrivien Quantrivien { get; set; }
    }
}
