//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_LuyenThiTracNghiem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quantrivien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quantrivien()
        {
            this.GIANGVIENs = new HashSet<GIANGVIEN>();
            this.HOCVIENs = new HashSet<HOCVIEN>();
            this.MONHOCs = new HashSet<MONHOC>();
            this.QUANLYCHUONGs = new HashSet<QUANLYCHUONG>();
        }
    
        public string MaAdmin { get; set; }
        public string TenAdmin { get; set; }
        public string Diachi { get; set; }
        public Nullable<decimal> SDT { get; set; }
        public string Email { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANGVIEN> GIANGVIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCVIEN> HOCVIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONHOC> MONHOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANLYCHUONG> QUANLYCHUONGs { get; set; }
    }
}
